all:
  hosts:
    aws_ec2:
      ansible_host: 54.236.23.117 # IP da instância EC2
      ansible_user: ubuntu # Ubuntu padrão
      ansible_ssh_private_key_file: '../terraform/EC2Tutorial.pem'
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
